"""Pipeline run report — formats and emails per-source stats after each run.

Required env vars (if omitted, sending is skipped with a warning):
    SMTP_USER      — Gmail address used as sender
    SMTP_PASSWORD  — Gmail App Password (16 chars, no spaces)

Optional env vars:
    REPORT_EMAIL_TO — recipient address (default: shipra.2507@gmail.com)
    SMTP_HOST       — SMTP host (default: smtp.gmail.com)
    SMTP_PORT       — SMTP port (default: 587)
"""

import logging
import os
import smtplib
import ssl
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

logger = logging.getLogger(__name__)

_REPORT_TO = os.environ.get("REPORT_EMAIL_TO", "shipra.2507@gmail.com")
_SMTP_HOST = os.environ.get("SMTP_HOST", "smtp.gmail.com")

_CELL = "padding:6px 12px;border:1px solid #ddd;white-space:nowrap;"
_HEAD = f"{_CELL}background:#f4f4f4;font-weight:600;"


def _avg(scores: list[int]) -> str:
    return f"{sum(scores) / len(scores):.1f}" if scores else "—"


def _build_html(
    run_id: str, summary: dict, per_source: dict, sources: list[str]
) -> str:

    rows = ""
    for src in sources:
        s = per_source[src]
        err_html = (
            "<br>".join(
                f"<span style='color:#c0392b'>{k}: {v}</span>"
                for k, v in sorted(s["hunter_errors"].items())
            )
            or "—"
        )
        rows += (
            f"<tr>"
            f"<td style='{_CELL}'>{src}</td>"
            f"<td style='{_CELL};text-align:center'>{s['qualifying']}</td>"
            f"<td style='{_CELL};text-align:center'>{_avg(s['scores'])}</td>"
            f"<td style='{_CELL};text-align:center'>{s['hunter_enriched']}</td>"
            f"<td style='{_CELL}'>{err_html}</td>"
            f"<td style='{_CELL};text-align:center'>{s['dispatched']}</td>"
            f"<td style='{_CELL};text-align:center'>{s['contacts_upserted']}</td>"
            f"<td style='{_CELL};text-align:center'>{s['dm_queue_written']}</td>"
            f"</tr>"
        )

    total_hunter_errors = sum(
        sum(s["hunter_errors"].values()) for s in per_source.values()
    )
    error_banner = ""
    if total_hunter_errors:
        error_banner = (
            f"<p style='color:#c0392b;font-weight:600'>"
            f"⚠ {total_hunter_errors} Hunter API error(s) across all sources — see table.</p>"
        )

    return f"""
<html><body style="font-family:sans-serif;color:#222;max-width:900px;margin:0 auto">
<h2 style="border-bottom:2px solid #3498db;padding-bottom:6px">
  Book Pipeline Run Report
</h2>
<p style="color:#666">Run ID: <code>{run_id}</code></p>

<h3>Overall Summary</h3>
<table style="border-collapse:collapse;margin-bottom:16px">
  <tr>
    <td style="{_HEAD}">Discovered</td><td style="{_CELL}">{summary.get("discovered", 0)}</td>
    <td style="{_HEAD}">Scored</td><td style="{_CELL}">{summary.get("scored", 0)}</td>
    <td style="{_HEAD}">Qualifying</td><td style="{_CELL}">{summary.get("qualifying", 0)}</td>
  </tr>
  <tr>
    <td style="{_HEAD}">Dispatched</td><td style="{_CELL}">{summary.get("dispatched", 0)}</td>
    <td style="{_HEAD}">Review Queue</td><td style="{_CELL}">{summary.get("review_queue", 0)}</td>
    <td style="{_HEAD}">Pipeline Errors</td><td style="{_CELL}">{summary.get("errors", 0)}</td>
  </tr>
</table>

{error_banner}

<h3>Per-Source Breakdown</h3>
<table style="border-collapse:collapse;font-size:14px">
  <thead>
    <tr>
      <th style="{_HEAD}">Source</th>
      <th style="{_HEAD}">Qualifying</th>
      <th style="{_HEAD}">Avg Score</th>
      <th style="{_HEAD}">Hunter Enriched</th>
      <th style="{_HEAD}">Hunter Errors</th>
      <th style="{_HEAD}">Dispatched</th>
      <th style="{_HEAD}">Contacts Upserted</th>
      <th style="{_HEAD}">DM Queue Written</th>
    </tr>
  </thead>
  <tbody>{rows}</tbody>
</table>

<p style="color:#aaa;font-size:12px;margin-top:24px">
  Generated by book-pipeline · {run_id}
</p>
</body></html>
"""


def _build_text(
    run_id: str, summary: dict, per_source: dict, sources: list[str]
) -> str:
    lines = [
        f"Book Pipeline Run Report — {run_id}",
        "",
        "OVERALL SUMMARY",
        f"  Discovered:    {summary.get('discovered', 0)}",
        f"  Scored:        {summary.get('scored', 0)}",
        f"  Qualifying:    {summary.get('qualifying', 0)}",
        f"  Dispatched:    {summary.get('dispatched', 0)}",
        f"  Review Queue:  {summary.get('review_queue', 0)}",
        f"  Errors:        {summary.get('errors', 0)}",
        "",
        "PER-SOURCE BREAKDOWN",
        f"  {'Source':<14} {'Qual':>4} {'AvgScore':>8} {'Enriched':>8} {'HunterErrs':>12} {'Dispatched':>10} {'Contacts':>9} {'DMQueue':>8}",
        "  " + "-" * 80,
    ]
    for src in sources:
        s = per_source[src]
        err_total = sum(s["hunter_errors"].values())
        err_str = str(err_total) if err_total else "—"
        lines.append(
            f"  {src:<14} {s['qualifying']:>4} {_avg(s['scores']):>8}"
            f" {s['hunter_enriched']:>8} {err_str:>12}"
            f" {s['dispatched']:>10} {s['contacts_upserted']:>9} {s['dm_queue_written']:>8}"
        )
        if s["hunter_errors"]:
            lines.append(f"\n  Hunter error detail — {src}:")
            for err_type, count in sorted(s["hunter_errors"].items()):
                lines.append(f"    {err_type}: {count}")

    return "\n".join(lines)


def send_run_report(run_id: str, summary: dict, per_source: dict) -> None:
    """Format and email the run report. Skips silently if SMTP is not configured."""
    smtp_user = os.environ.get("SMTP_USER", "")
    smtp_password = os.environ.get("SMTP_PASSWORD", "")
    smtp_port = int(os.environ.get("SMTP_PORT", "587"))
    if not smtp_user or not smtp_password:
        logger.warning(
            "Run report not sent: SMTP_USER / SMTP_PASSWORD not set in environment."
        )
        return

    qualifying = summary.get("qualifying", 0)
    discovered = summary.get("discovered", 0)
    subject = (
        f"Pipeline Run Report — {run_id} "
        f"({discovered} discovered, {qualifying} qualifying)"
    )

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = smtp_user
    msg["To"] = _REPORT_TO

    sources = sorted(per_source.keys())
    msg.attach(MIMEText(_build_text(run_id, summary, per_source, sources), "plain"))
    msg.attach(MIMEText(_build_html(run_id, summary, per_source, sources), "html"))

    try:
        context = ssl.create_default_context()
        with smtplib.SMTP(_SMTP_HOST, smtp_port) as server:
            server.ehlo()
            server.starttls(context=context)
            server.login(smtp_user, smtp_password)
            server.sendmail(smtp_user, _REPORT_TO, msg.as_string())
        logger.info("Run report emailed to %s", _REPORT_TO)
    except Exception as exc:  # noqa: BLE001 - best-effort email delivery; SMTP failures must not crash the pipeline
        logger.error("Failed to send run report email: %s", exc)
